dist: trusty

language: php
php:
    - '7.2'
    - '7.3'

addons:
    sonarcloud:
        organization: "nabu-3-github"

script:
    - phpunit --bootstrap common.php tests --coverage-clover phpunit.coverage.xml
    - sonar-scanner
