dist: trusty

language: php
php:
    - '7.2'
    - '7.3'

addons:
    sonarcloud:
        organization: "nabu-3-github"

install:
    - sudo mkdir -p /etc/opt/nabu-3.conf.d
    - composer require nabu-3/provider-mysql-driver

script:
    - phpunit --bootstrap common.php tests --coverage-clover phpunit.coverage.xml --whitelist nabu
    - sonar-scanner
