dist: trusty
sudo: false
language: php

addons:
    sonarcloud:
        organization: "nabu-3-github"

install:
    - if [ -f composer.lock ]; then rm composer.lock; fi
    - travis_retry composer update

script:
    - ./bin/phpunit --bootstrap common.php tests --coverage-clover phpunit.coverage.xml --whitelist nabu
    - sonar-scanner

cache:
    directories:
        - $HOME/.composer/cache

jobs:
    include:
        - stage: Test
          env: DB=mysql MYSQL_VERSION=5.7
          php:
              - 7.2
              - 7.3
              - 7.4snapshot
          before_script:
              - sudo apt-get install -y realpath
              - ./tests/travis/install-mysql-$MYSQL_VERSION.sh
              - bin/nabu-install.sh
                    --etc-path=`pwd`/etc/opt/nabu.conf.d
                    --base-path=`pwd`
                    --web-path=`pwd`/var/opt/nabu-3
                    --log-path=`pwd`/var/log/nabu-3
                    --db-host=localhost
                    --db-port=3306
                    --db-schema=nabu-3
                    --db-user=nabu-3
                    --db-password=nabu-3
                    --silent
          sudo: required

    allow_failures:
        - env: DB=mysql MYSQL_VERSION=5.7
