dist: trusty
sudo: false
language: php

addons:
    sonarcloud:
        organization: "nabu-3-github"

install:
    - rm composer.lock
    - travis_retry composer update

script:
    - phpunit --bootstrap common.php tests --coverage-clover phpunit.coverage.xml --whitelist nabu
    - sonar-scanner

cache:
    directories:
        - $HOME/.composer/cache

jobs:
    include:
        - stage: Test
          env: DB=mysql MYSQL_VERSION=5.7
          php: 7.2
          before_script:
              - ./tests/travis/install-mysql-$MYSQL_VERSION.sh
          sudo: required

    allow_failures:
        - env: DB=mysql MYSQL_VERSION=5.7
