dist: trusty

language: php
php:
    - 7.2
    - 7.3
    - 7.4snapshot

env:
    - DB=mysql
    - MYSQL_VERSION=5.7

addons:
    sonarcloud:
        organization: "nabu-3-github"

install:
    - travis_retry composer update

before_script:
    - ./tests/travis/install-mysql-$MYSQL_VERSION.sh

script:
    - phpunit --bootstrap common.php tests --coverage-clover phpunit.coverage.xml --whitelist nabu
    - sonar-scanner

cache:
    directories:
        - $HOME/.composer/cache
